### ISSUE TITLE
Please add release tags

### ISSUE THREAD

**Issue by tillea** [PacificBiosciences/pbbarcode#3]
Hi,
I'm currently working on the Debian package of pbbarcode.  It would be really helpful if you would add release tags to enable the Debian maintainers to detect new versions of your software to keep the Debian package in sync with your code.
Thanks for considering, Andreas.

**Comment by dalexander** [comment]
this is a deprecated repo.

**Comment by tillea** [comment]
Hi David,

On Mon, Jan 16, 2017 at 08:52:00AM -0800, David Alexander wrote:
> this is a deprecated repo.  

OK, understand.  However, what about simply tagging the latest release
anyway.  IMHO a simple

    git tag 0.8.0
    # at least if this is the currect number as I can see it
    git push --tags

is faster done than discussing the status of the repository.

Thanks for considering

       Andreas.

PS: Adding the information that the repository is deprecated somewhere
    would help as well for sure. :-)

-- 
http://fam-tille.de

**Comment by dalexander** [comment]
Sure, I did that

**Comment by tillea** [comment]
On Mon, Jan 16, 2017 at 07:13:08PM -0800, David Alexander wrote:
> Sure, I did that

Thanks, I've updated Debian metadata about this.

-- 
http://fam-tille.de
